### ISSUE TITLE
Database Size: api_check and django_session tables

### ISSUE THREAD

**Issue by stevenmcastano** [healthchecks/healthchecks#102]
I've been running healthchecks for a while now and I LOVE it. To manage the database size I made a cron job to run once a week to run "prunepings" to bring the database back down to size a little bit before optimizing my MariaDB tables, however, I noticed that the database seems to just keep growing and growing even though I haven't added many more checks.

So I decided to get in and took at the tables and their contents. It looks like the api_check table has almost 600,000 rows in it and I only have about 20 checks in the whole system. Upon looking at it closer, there are a huge number of rows with unique "code" values, but everything is is basically NULL or set to default values and they all are listed as "status" "new". Any idea why these are there? Can I just delete them? Is there another command to get ride of these and/or prevent them from coming back?

Then the same this is happening with the django_session table. There are a huge number of "session_key" and "session_data" values in there, but almost all of them have expiration dates long in the past? Can these be deleted manually and/or via a command line option?

Right now, those two tables take up 93 and 142MB respectively which is basicallu 95%+ of my entire database size. I'd love to trim that down somehow.

**Comment by cuu508** [comment]
Hi @stevenmcastano,

check out the [Database Cleanup](https://github.com/healthchecks/healthchecks#database-cleanup) section in README. The `prunechecks` management command will clean up the `api_check` table.  

Here's why the checks are accumulating: every time someone visits the welcome page, the system creates a new check and associates it with the user's session. If the user signs up, this check gets assigned to them. Otherwise, it just stays in `api_check` table. If you have a monitoring service like Pingdom fetching the welcome page once a minute, there will be a new check created once a minute. 

For cleaning up django sessions, there's a [clearsessions](https://docs.djangoproject.com/en/1.10/ref/django-admin/#django-admin-clearsessions) management command.

**Comment by stevenmcastano** [comment]
Ah, that makes total sense. What I actually have is haproxy running for load balancing with nginx in front of it for SSL. So actually twice a minute the load balancer hits the front page. I’ll definitely run both of those commands and clean that stuff up. I’m sure I can write a cronjob to clean them out once a week as well.

What would really be nice would be if there was some sort of health check page we could hit that maybe quickly runs some PHP code to check the DB connection and if everything is good return “OK” with an HTTP 200, if not, return a “FAIL” with a HTTP 500. That would be enough that that I could point the load balancer at that page instead of the wrong one and generate all these extra sessions.

That being said, I guess I could just create a ping for it too! hahaha

**Comment by cuu508** [comment]
Exactly, you can create a check specifically for this. As a bonus, you'll get a notification if haproxy stops pinging it...
