### ISSUE TITLE
Support FAIL, not just DOWN, in email subject line

### ISSUE THREAD

**Issue by jdkratz** [healthchecks/healthchecks#1037]
It would be helpful if the alert email subject line distinguished between DOWN (I.e. missed ping) and FAIL (explicitly triggered fail). Not at all a major issue, it would just provide more information at a glance.

**Comment by cuu508** [comment]
The email body has "Last Ping Type" field which can tell you this. If it says "success", then the check is going down because last success was too long ago. If it says "failure" or "exit code x", the check received a failure signal.

**Comment by jdkratz** [comment]
Yes, I understand that. I’m just suggesting that that info be in the email subject line as well as the body. I get email alerts on my watch, but those alerts only show the subject line. It would be great to be able to tell what kind of failure it is a without needing to open the email. Again, definitely not a big deal, just a suggestion.

(Also, this is SUCH a great service, many thanks for keeping it that way for 9 years!)

**Comment by cuu508** [comment]
Thanks for the additional details, @jdkratz!

I would like to leave the subject line format as-is for backwards compatibility. Existing users are likely already relying on the current formatting (`UP|DOWN <separator> <name of the check>`). If we change the logic to use FAIL instead of DOWN in some cases, some email filtering and automation will likely break and cause issues. I also don't want to add this as a configurable option–each extra configuration knob adds complexity.
