### ISSUE TITLE
Add check badge URLs to API

### ISSUE THREAD

**Issue by kennethjor** [healthchecks/healthchecks#1100]
#960 adds badges for individual checks. Thank you for that, it's something I've wanted for a while.

It would be great if the `checks` (or other) API endpoint returned the URLs for these too.

**Comment by cuu508** [comment]
Thanks for the suggestion!

The UUIDs in badge URLs and in the ping URLs are different. This is intentional, we don't want people just with access to a check's badge URL be able to ping the check. 

In the database, the UUIDs for badge URLs (`Check.badge_key` field) are not filled in by default. They are filled in on-demand, when the user selects the check in the "Badges" page. 

If we added a new "badge_url" field in the output of the `checks` API call, it would most of the time be null because the corresponding badge_key is null. 

We could have an API call for generating a badge URL for a specific check, perhaps something like:

    POST https://healthchecks.io/api/v3/checks/<uuid>/generate_badge_key

This would fill in the check's `badge_key` field (if it's not filled in already), then put together and return a badge URL. Would something like this be useful?

**Comment by kennethjor** [comment]
@cuu508 Personally, if the URL field is only populated after it has been generated, that's fine with me, even if I have to look at it in the UI first.

Is there a reason it's generated on-demand? Why not just always generate it?

**Comment by cuu508** [comment]
> Is there a reason it's generated on-demand? Why not just always generate it?

When I was adding support for per-check badges, it was easier to populate them on-demand, rather than writing a data migration to backfill the existing checks. Plus a slight space saving. 

But if we're going to expose badge URLs in API responses, , it would be cleaner and simpler both for the server and the clients to always generate it, rather than have a new API call, and having a sometimes-null field in API responses.
