### ISSUE TITLE
No server is available to handle this request.

### ISSUE THREAD

**Issue by hackedbellini** [healthchecks/healthchecks#121]
Since an hour ago all requests to hchk are failing. For example:

```
$ curl https://hchk.io/<uuid>                                                                                                                                                  
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```

**Comment by ashiddo11** [comment]
Experiencing the same issue as well

**Comment by szepeviktor** [comment]
@cuu508 All of my servers say the same

Could we help?

**Comment by devsibwarra** [comment]
Posting an update that my checks are being handled successfully at this time

**Comment by hackedbellini** [comment]
Yeah, it seems to be fixed now.

**Comment by szepeviktor** [comment]
This is a public report on hchk: https://hetrixtools.com/report/uptime/ab96e2feb17771d0f94791eadfff0158/

**Comment by cuu508** [comment]
Thanks for reporting this issue -- much appreciated!
The hosting setup has changed significantly since April, making this issue obsolete -- so I'll be closing it.
To give some background, I recently finished an article that goes in some detail on healthchecks.io hosting setup, and what issues I had run into: https://medium.com/@healthchecks/the-evolution-of-healthchecks-io-hosting-setup-4fa0d249a35a
