### ISSUE TITLE
Registration - Email me a link- Incorrect email address

### ISSUE THREAD

**Issue by red-erik** [healthchecks/healthchecks#192]
Hi,
Great job so, first of all, thanks. 
Email are working and I'm able to invite other users but the registration process always return "Incorrect Email Address".
REGISTRATION_OPEN = True
but no one is able to register and receive a link.
Another thing is that the admin page has no different option from the standard one. Witch is it's purpose ?
Regards.

Red.

**Comment by cuu508** [comment]
Hi, 

When you get the "Incorrect Email Address", are you on the /accounts/login/ page?
If so, the forms there don't handle new user registration. They only do login for already existing users.

To register as a new user, go to the front page ("/") and click on "Sign Up – It's Free" button – it should open a "Create Your Account" dialog:

![image](https://user-images.githubusercontent.com/661859/47085218-9f675000-d21e-11e8-8c1e-c6d9623169a0.png)

**Comment by cuu508** [comment]
For development, I just run them separately.
For production, it's a good idea to use uwsgi or gunicorn instead of the "./manage.py runserver".

With uwsgi, one option is to use "--attach-daemon" configuration directive. As a starting point, drop the following `uwsgi.ini` in your project directory:

```
[uwsgi]
http-socket = :8000
enable-threads
plugin = python3
module = hc.wsgi:application
static-map = /static=static-collected
static-gzip-dir = static-collected/CACHE
attach-daemon = ./manage.py sendalerts
```

And run uwsgi like so:

    uwsgi --ini uwsgi.ini

uwsgi will start a sendalerts subprocess on startup, and will kill it on exit.

On https://healthchecks.io I run the sendalerts command separately, as  a systemd service. This way I can start and stop the web server and the background processes individually. The .service file I'm using is:

```
[Unit]
Description=sendalerts
After=network-online.target
Wants=network-online.target

[Service]
Slice=machine.slice
Restart=always
RestartSec=20
StartLimitInterval=10
StartLimitBurst=5

User=www-data
Group=www-data

ExecStart=/usr/bin/python3 -u /path/to/healthchecks/manage.py sendalerts --no-threads

PrivateDevices=true
ProtectHome=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target

```

**Comment by red-erik** [comment]
Thank You very much for this explanation. I already created a service for  for ./manage.py runserver 0.0.0.0:8000. Now I'll try to create a second service using your suggestion.
Great software and thank You again for sharing.
Regards.

Red.
