### ISSUE TITLE
Problem with cron expressions

### ISSUE THREAD

**Issue by LordMike** [healthchecks/healthchecks#196]
Hi,

Very odd. The cron expression engine does not accept `0 2 * * *`... It accepts `0 1 * * *` and `0 3 * * *`.

![image](https://user-images.githubusercontent.com/1027111/47313789-1f871e80-d640-11e8-9b4c-4cb36e524494.png)

![image](https://user-images.githubusercontent.com/1027111/47313802-2746c300-d640-11e8-9dda-ca75e8cfcb7c.png)

![image](https://user-images.githubusercontent.com/1027111/47313827-3fb6dd80-d640-11e8-9500-03647f997f70.png)

**Comment by LordMike** [comment]
Indeed. Denmark/Copenhagen should be at +2 now, but we're changing in a few days (28th).

I imagine that's the issue. If I go for once a month, I get the correct offsets (we go to +1 there):

![image](https://user-images.githubusercontent.com/1027111/47314436-efd91600-d641-11e8-91ce-472fc2d4810f.png)

... but then this works, so maybe that was a red herring..

![image](https://user-images.githubusercontent.com/1027111/47314455-02ebe600-d642-11e8-941e-e1ed733f2dc0.png)

**Comment by cuu508** [comment]
This was indeed due to DST transitions. When clocks are rolled one hour back or forward, some local times happen *twice* and some are skipped over. Worked around the ambiguity but will need to do more investigation on how to best handle time jumps in March when DST starts.

This is a hairy problem. I would recommend to keep things simple and:
* use UTC on your servers
* if you're not using UTC, avoid scheduling cron jobs around 2-3AM local time ;-)

**Comment by pkoziol** [comment]
> handle time jumps in March when DST starts

I believe European Commision (or Parliament?) voted/recommended recently to stop using DST, so this was probably the last time we changed our clocks in (most of?) the Europe.

**Comment by LordMike** [comment]
They're not done yet. It's still in discussion, and the timetable differes between 2019 and 2021. We'll see :P
