### ISSUE TITLE
Feature Request: change category badge status to partially down

### ISSUE THREAD

**Issue by BioTheWolff** [healthchecks/healthchecks#251]
I am doing a status page and made a check fail for test purposes. I saw that if one check is down, all the categories it belongs to are noted "down". Could we add a orange-ish color and a "Partially Down" state if the category has up checks and down checks ?

**Comment by cuu508** [comment]
The orange color is currently used to indicate the "in grace period" status. The rules are:

 * If any matching check is down, the badge is red
 * Otherwise, if any matching check is in the grace period, the badge is orange
 * Otherwise the badge is green

The badges have SVG and JSON versions:

![image](https://user-images.githubusercontent.com/661859/57683851-3c675b80-763d-11e9-9f45-8a7eaf85d83a.png)

We cannot easily change the behaviour of the SVG badges because people are already relying on their current behaviour. We can, however, add more fields in the JSON ones. Say, instead of returning

    {"status": "down"}

return a few more fields:

    {"status": "down", "up": 15, "grace": 0, "down": 1}

On the status page side you could then  fetch the JSON and format it as a badge or a dashboard widget locally. How does that sound?

**Comment by BioTheWolff** [comment]
Sounds really great ! In addition to allowing the users to get more informations, you give numbers that can be displayed too ! I like the idea, it is totally the answer i expected. Thanks :p 
Tell me if you want to implement it right now or later, i don't care much about the date :)

**Comment by cuu508** [comment]
@BioTheWolff I've now deployed this change. Feel free to check it out when you get a chance.

I decided to go with this format:

    {"status": "down", "total": 16, "grace": 0, "down": 1}

I used "total" instead of "up", because checks can also be in "new" and "paused" states – it would be inaccurate to count them as "up".
