### ISSUE TITLE
Ability to select valid authentication modes

### ISSUE THREAD

**Issue by dalee-bis** [healthchecks/healthchecks#269]
Due to security requirements, we may not be allowed to use login links for accounts. Would it be possible to add an option so that this can be disabled for an account? Something like a setting on the account which allows you to select valid login options from Login Link, Password or Both.

**Comment by cuu508** [comment]
Yes, that could be added. Would have to think what to do in "Forgot Password" cases then too.

Out of curiosity, what's the rationale for that requirement?

**Comment by dalee-bis** [comment]
Good point about the forgot password.

It's when using a mailing list for the login. It's a single point of failure if only one person has administrator on an account (which I believe is the current setup with Owner and Member?).

The idea was to use a mailing list for the main account and have only a small team with access to the password for admin access (very infrequently required). The practice is already in place of limiting access to a password so it would be an easier sell to the security board than having to define how we protect from anyone who is on a mailing list gaining access. I expect the login links are technically more secure but, from a social engineering perspective, it's much easier to get yourself added to a mailing list than to gain access to a password safe.

**Comment by cuu508** [comment]
OK, to repharase (and make sure I understand correctly):

* You would prefer to use a mailing list over a single user's email for login, to guard against the single user losing access, and so the whole organization losing access
* But, you would prefer password-only login over a mailing list, because access to password vault is easier to guard than access to the mailing list

If that's accurate, how about:

* Create a dedicated email address that will own the Healthchecks account. For example, healthchecks-admin@myorg.com
* Store credentials for *that* email address in the password vault
* To make logging into Healthchecks.io easier, also set a password on the account, and store that password in the vault too

How does that sound?

Just for reference, in case it's useful, here's what I currently do when I get requests to restore lost access. Say, an employee leaves the company and their colleague wants to take over the company account. In these cases I contact the former employee and get their consent to transfer the ownership. If that's not possible, but the new colleague 1) has the same company-specific email domain 2) is already a team member, that's good enough too and I transfer the ownership.
