### ISSUE TITLE
"manage.py migrate" throws an error when using sqlite

### ISSUE THREAD

**Issue by kchaitu4** [healthchecks/healthchecks#284]
Hello,

I am trying to setup healthcheck and when I run the below createsuperuser cmd, I am getting an error. Could someone please help me with this?

./manage.py createsuperuser
/root/webapps/healthchecks/hc/settings.py:214: UserWarning: local_settings.py not found, using defaults
  warnings.warn("local_settings.py not found, using defaults")

You have 19 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): api, auth, contenttypes, payments, sessions.
Run 'python manage.py migrate' to apply them.

Thanks in Advance,
Krsihna

**Comment by cuu508** [comment]
Hello,

did you run `./manage.py migrate`? What database backend are you using (postgres/mysql/sqlite)? Are you running the current master version of the code, or one of the releases?

**Comment by kchaitu4** [comment]
Yes I ram the migrate cmd. i am using default sql. Current master code

**Comment by cuu508** [comment]
By default sql I assume you mean sqlite. Did the migrate command complete successfully?

I recently bumped on a what appears to be a Django bug, affecting sqlite and migrations: https://code.djangoproject.com/ticket/30754

If the migrate command finishes with a "django.db.utils.OperationalError: no such column: new__api_check.status" error, you are hitting the same bug. 

In that case, you can then do one of the:
 * use PostgreSQL (recommended) or MySQL
 * instead of running the master branch, grab the most recent release (1.9.0) and use that. 

I won't make a new release until the linked sqlite bug is fixed, or I've worked around it some other way.

**Comment by kchaitu4** [comment]
Thanks...Now I am seeing a new error when I run ./manage.py createsuperuser

django.db.utils.IntegrityError: NOT NULL constraint failed: auth_user.last_login. 

I am now not able to create a super user.

**Comment by cuu508** [comment]
Did you switch to 1.9.0 release? If so, try deleting the .sqlite file and start over with a fresh one.

**Comment by kchaitu4** [comment]
what is the url to clone 1.9.0 release?

**Comment by cuu508** [comment]
You can use your existing checkout:

```
git fetch --tags
git checkout v1.9.0
```

**Comment by kchaitu4** [comment]
it worked after switching to v1.9.0. Thanks.

**Comment by cuu508** [comment]
Good! 

I'll leave this ticket open until the sqlite migrations bug gets resolved – other people might run into it as well.
