### ISSUE TITLE
CSRF for iframe

### ISSUE THREAD

**Issue by BobCashStory** [healthchecks/healthchecks#326]
i need to be able to configure CSRF_COOKIE_DOMAIN from django, to allow my main domain like exemple.com .
Then make login in iframe work.
 like healtcheck is healtcheck.exemple.com an  iframed into main.exemple.com

**Comment by cuu508** [comment]
I'd like to understand the problem a little better.

A. Is the login form served on a different domain? I.e., you have a centralized login form which takes username and password, and submits it to a Healthchecks instance running somewhere else?

This would try to do exactly what CSRF protection is supposed to prevent. So CSRF protection would have to be switched off. A better solution would be to look into implementing some form of SSO.

B. Or is the login form still served by Healthchecks, but everything is enclosed in an iframe, in order to add a custom header or footer?

With some hacks this can work:

* Comment out `django.middleware.clickjacking.XFrameOptionsMiddleware`
* Add `CSRF_COOKIE_SAMESITE = None`
* Add `SESSION_COOKIE_SAMESITE = None`

But the user experience would be pretty bad: cannot see the URL in address bar, cannot bookmark pages, cannot link directly to check details pages, potential double vertical scrollbars. If you need custom header/footer it would be better to edit the base template.

**Comment by BobCashStory** [comment]
B.  the login form still served by Healthchecks !

But in fact the last update you made with the fix Don't set CSRF cookie on first visit. Signup is exempt from CSRF protection make it work for my side !
I though you fixed it because of my issue, ahah, thanks :)
