### ISSUE TITLE
The new /api/v1/metrics/ endpoint is not documented

### ISSUE THREAD

**Issue by mountaindude** [healthchecks/healthchecks#375]
Can't find any documentation for this new endpoint, so it's been a bit trial and error finding it, so far no luck. Running as Docker container, exposing healthchecks on port 8000.

Tried things like 
http://myurl:8000/api/v1/metrics/
http://myurl:8000/admin/api/v1/metrics/

What's the correct URL, and is it documented somewhere?

Thx

**Comment by mountaindude** [comment]
Partly caused by myself being new to Healtchchecks. 
I enabled API access a project, then used the generated API key in the X-Api-Key HTTP header. 
Works when doing a GET on the /api/v1/checks/ endpoint, but the /api/v1/metrics/ returns a "403 Forbidden" error.

**Comment by cuu508** [comment]
Sorry – it's undocumented at the moment. I wanted to expose a few service-wide metrics to be used in a [status page](https://status.healthchecks.io/). I didn't want this to be world-public, so added the `METRICS_KEY` environment value. If the client specifies a correct key, they get a response, otherwise they get 403. I mentioned this in CHANGELOG but didn't document it.

Are you interested in instance-wide metrics, or per-project metrics?

**Comment by mountaindude** [comment]
That's totally fine, no problem. I know but too well how many things need fixing when doing these kind of releases.

I'd be interested in both project specific and global metrics, I guess.

Most of all I'm interested in a way to get a history for run-times (#371). This is not possible in the current API, from what I understand. I have on my todo list to pull the data from the db, but an API would of course be nice.
