### ISSUE TITLE
unpausing checks that glitch out

### ISSUE THREAD

**Issue by diwu1989** [healthchecks/healthchecks#38]
![image](https://cloud.githubusercontent.com/assets/380950/12670087/82f2d3ee-c61a-11e5-857b-1e49f7c6dc94.png)

**Comment by cuu508** [comment]
What I'm planning to do is to get rid of the  "stopped" state. 

Suppose you have multiple channels set up, let's say an email and a Slack webhook. And the webhook URL is obviously invalid, because of copy-pasting mishap. 

What happens currently: the first time we try posting to Slack and fail, we mark the check as "paused" and give up forever. Even though the email channel might still be viable and useful. 

What I think should happen: check never goes into "paused" state. If a posting to a channel fails, we store the most recent failure message and display it on "Channels" page, add a note about it in monthly report etc. Failures might also be temporary and it is worth retrying later.

**Comment by diwu1989** [comment]
yeah deal that sounds way better, i hit a hiccup with slack recently and some of my checks got paused

**Comment by cuu508** [comment]
This is now implemented: checks don't go into "paused" state. If there is a problem with one of the channels, it will be indicated on "Integrations" page, but rest of the channels still work.
