### ISSUE TITLE
Change DB

### ISSUE THREAD

**Issue by aleqcz** [healthchecks/healthchecks#389]
Hi, 
is it possible to migrate the DB from one type to another? Namely SQLite to PostgreSQL?
Thanks, Best regards,
A.

**Comment by SuperSandro2000** [comment]
Dump the db of one software to sql and import it into the other.

**Comment by aleqcz** [comment]
Thanks, quite easy in the end

**Comment by immanuelfodor** [comment]
That moment when you find the related ticket for your current problem :grinning: 

![image](https://user-images.githubusercontent.com/21174107/103208148-37cde480-4900-11eb-96bf-23f7408ecf3a.png)

**Comment by immanuelfodor** [comment]
In hindsight, I'd go for `pgloader` and migrate the whole DB instead of just the checks :grinning: it seemed easier at first but turned out to be more complex than expected :sweat_smile: but here are my notes anyway for the poor souls who find this issue later.

Start the project with PG DB, let migrations run, create your new user and project, then login to the PG DB:

```bash
sudo -u healthchecks psql
healthchecks=> \d+
# lists the PG objects
healthchecks=> select * from accounts_project;
# note your project ID, we need this later
```

Dump the `api_check` table from the old DB:

```bash
sqlite3 config/hc.sqlite
sqlite> .dump api_check
# CTRL+D to exit
```

Grab the INSERT INTO statements into a text editor:
- Replace all old project ID references to the new project ID if the ID has been changed. In my case, I needed to replace 1->2, so I did a simple `,1,NULL,'','',0);`->`,2,NULL,'','',0);` replacement at the end of each query
- Zero out all ping counters by replacing `,[0-9]+,'(simple|cron)'`->`,0,'\1'`
- Remove all IDs from the inserts and also provide all fields except the ID to the inserts to use the auto increment IDs (sequence) in PG: `api_check VALUES\([0-9]+,`->`api_check ("code","last_ping","alert_after","status","timeout","name","created","grace","tags","n_pings","kind","schedule","tz","has_confirmation_link","last_ping_was_fail","desc","last_start","subject","project_id","last_duration","methods","subject_fail","manual_resume") VALUES(`
- Replace interval bigints to PG intervals:
  - `86400000000`->`'1 day'`
  - `3600000000`->`'1 hour'`
  - `604800000000`->`'1 week'`
  - any other values to their equivalents
- Replace all char functions to the PG equivalent: `char(`->`CHR(`
- Replace all bool integers to PG bools, in my case: `,0,0,`->`,FALSE,FALSE,` and `,0);`->`,FALSE);`

Copy-paste all the statements into the PG CLI, and it should be fine. 

Subscribe all checks to all the notification channels with `insert into api_channel_checks select row_number() over () as id, channel_id, check_id from (select id as channel_id from api_channel where project_id=2) t1, (select id as check_id from api_check where project_id=2) t2;` just replace the project ID to your new one.

**Comment by cuu508** [comment]
Thanks for posting your notes, @immanuelfodor !

Out of curiosity, how did you decide to migrate from SQLite to Postgres? Did you have any specific problems with SQLite? Or are you planning to run multiple load-balanced web servers?

**Comment by immanuelfodor** [comment]
`pgloader` version below as I've found some inconsistencies using the above search-and-replace method. Namely, any new check would not turn on notification channels: turns green when clicked, reload the page, then all gray again. I probably missed something else in some other tables. However, the below method **doesn't work**, the `api_check` table's `interval` fields are making the migration fail, `pgloader` can't handle the conversion. At this point, the search-and-replace method at least works with the inconvenience to manually assign notification channels to checks in the DB for any newly created checks. I really don't know how @aleqcz found this migration "quite easy" :grinning: 

Create a new empty PG DB for Healthchecks, run the container to do all the migrations but do not do anything else. Stop the container to make this sure.

Install `raven-release` repo to avoid manually compiling `pgloader` for CentOS, then install it: (I did this over CentOS Stream which was upgraded from CentOS 8)

```bash
dnf install https://pkgs.dyn.su/el8/base/x86_64/raven-release-1.0-1.el8.noarch.rpm
dnf install pgloader
```

Create the following `pgloader` plan file called `health.load` next to the SQLite file based on https://pgloader.readthedocs.io/en/latest/ref/sqlite.html 

```
load database
     from sqlite://hc.sqlite
     into postgresql://yourpgsqluser:yourpgsqlpassword@yourpgsqlserver:yourpgsqlport/yourpgsqldatabase
     WITH include no drop, create no tables, truncate, create no indexes, reset sequences, data only
;
```

Run the command `pgloader health.load`, there might be warnings but that's fine, the main problem is the following error:

```
2020-12-29T15:56:10.692000+06:00 ERROR Database error 22015: interval field value out of range: "86400000000"
CONTEXT: COPY api_check, line 1, column timeout: "86400000000"
2020-12-29T15:56:10.803000+06:00 LOG report summary reset
                table name     errors       rows      bytes      total time
--------------------------  ---------  ---------  ---------  --------------
                     fetch          0          0                     0.000s
           fetch meta data          0         43                     0.028s
         Drop Foreign Keys          0         36                     0.012s
                  Truncate          0         21                     0.283s
--------------------------  ---------  ---------  ---------  --------------
         django_migrations          0        132     7.7 kB          0.083s
    auth_group_permissions          0          0                     0.044s
          auth_user_groups          0          0                     0.057s
auth_user_user_permissions          0          0                     0.023s
          accounts_project          0          1     0.1 kB          0.081s
        api_channel_checks          0         62     0.5 kB          0.085s
           api_tokenbucket          0          3     0.2 kB          0.110s
           auth_permission          0         64     2.4 kB          0.118s
     payments_subscription          0          0                     0.138s
                  api_ping          0       4088   320.1 kB          0.237s
          django_admin_log          0          0                     0.021s
                  api_flip          0         25     1.7 kB          0.065s
       django_content_type          0         16     0.3 kB          0.042s
                auth_group          0          0                     0.069s
            django_session          0          4     1.2 kB          0.098s
          accounts_profile          0          2     0.1 kB          0.104s
               api_channel          0          2     0.9 kB          0.176s
                 api_check          1          0                     0.163s
          api_notification          0         65     4.7 kB          0.178s
           accounts_member          0          0                     0.180s
                 auth_user          0          2     0.4 kB          0.188s
--------------------------  ---------  ---------  ---------  --------------
   COPY Threads Completion          0          4                     0.262s
           Reset Sequences          0         20                     0.027s
       Create Foreign Keys          0         18                     0.010s
          Install Comments          0          0                     0.000s
--------------------------  ---------  ---------  ---------  --------------
         Total import time          1       4466   340.2 kB          0.299s
```

You can see from the table, that no checks have been migrated because of this (0 rows). :sob: 

I'm so happy that I've kept the previous search-and-replace migrated DB, at least it's usable, however, a bit inconvenient to fiddle with the DB upon creating new checks to enable notification channels for them :grinning:

**Comment by immanuelfodor** [comment]
@cuu508 I'm moving my Healthchecks instance from a simple docker-compose install to Kubernetes. The nodes mount a shared NFS storage, and SQLite DBs are known to be not usable over NFS: locking problems first then DB corruption. I've already burned myself with this some time earlier. Since Helathchecks support PG over IP, the natural choice is to migrate it to PG, instead of using `hostPath` volumes with fixing the Healthcheck pod to that one node that has the SQLite file, or provisioning shared block storage to continue using SQLite (Ceph, etc). 

If there would be an export/import function in Healthchecks to ease the migration with an intermediary file format (JSON, XML, YAML, etc), it would be great to avoid DB-level operations :tada:
