### ISSUE TITLE
Dynamic HCs for ephemeral nodes for a service

### ISSUE THREAD

**Issue by pataquets** [healthchecks/healthchecks#42]
First of all, thank you for this great software and making it available.
I would like to perform health checks for services and batch jobs which should run always, but are run from different servers/nodes by autoscaling them.
For example:
- serviceA:instance1
- serviceA:instance2
- serviceA:instance3
- serviceB:instance1

The service should be always on, but instance count and name would vary with time. The service list is always the same and would be fine to maintain it by hand. But instances aren't always the same and names/identifiers can't be known in advance.
Would be great if instances could self-register themselves for a specific service kind to start being monitored. For those temporary instances, a single alert about each one leaving would suffice.
As of now, uuids have to be created ahead of time, but:
- Can pings to an uuid have added any kind of info with the instance name that could work?
- Can uuids be created dynamically via an API?
- Is there any way to remove the need to create uuids beforehand (on the fly)?

IMHO, this kind of usage makes a lot of sense in the age of cloud.
Thanks in advance.

**Comment by cuu508** [comment]
@pataquets check out #45

I've started work on a command line client, which should help with this use case: 

* create a check if it does not exist
* take note of its ping URL
* ping it 

The client code (very alpha for now) is at https://github.com/healthchecks/hchk

    Can pings to an uuid have added any kind of info with the instance name that could work?

Not at the moment. I've seen some people sending custom data in User-Agent header of the ping, but that's more of a hack.

    Can uuids be created dynamically via an API?

Since today, yes! – https://healthchecks.io/docs/api/

    Is there any way to remove the need to create uuids beforehand (on the fly)?

UUIDs are created on server, so it is not possible for the client to generate UUID deterministically and then feed it to the server. However, the client can create a check via API, store its ping URL locally and reuse it.

**Comment by pataquets** [comment]
Much appreciated, thanks a lot.
Tried it, but got an error. Filed an issue in the hchk repo.
