### ISSUE TITLE
Support multiple schedules

### ISSUE THREAD

**Issue by adepertat** [healthchecks/healthchecks#448]
The cron syntax is very nice, but what if I need to check for something running at 12:00 and 17:30 ? AFAIK this can't be done with the regular cron syntax and in a crontab I would have two lines. A solution would be to have mutiple schedules enabled for one check.

Great software by the way, very easy and useful.

**Comment by msdos** [comment]
From an implementation POV, I think all checks, by default, don't have a schedule.

If a check implements a schedule, all down events outside schedule hours would be ignored. In "Current Status" for example, instead of when outside schedule hours:

`This check is up. Last ping was 55 seconds ago.`

We could have:

`This is a scheduled check. No ping is being monitored between <schedule range>.`

When time comes for the schedule hours, the same interface and functionality right now would be used.

This is a really nice addition. I have some checks that I didn't create because I only need them on working hours.

**Comment by msdos** [comment]
> AFAIK this can't be done with the regular cron syntax

What about https://stackoverflow.com/questions/11914445/run-a-cron-job-every-minute-only-on-specific-hours?

For example:

> It will only check every minute from 11AM to 12AM, 4PM to 5PM and 9PM to 10PM

`* 11,16,21 * * *`

**Comment by cuu508** [comment]
This is now possible with OnCalendar schedules: https://blog.healthchecks.io/2023/12/oncalendar-schedules-monitor-systemd-timers-with-healthchecks-io/
