### ISSUE TITLE
RocketChat Integration

### ISSUE THREAD

**Issue by scornet256** [healthchecks/healthchecks#463]
I'm using the Mattermost integration with my RocketChat instance, which works perfectly.
Just wanted to let you or others know.

**Comment by fbartels** [comment]
I can confirm this

**Comment by cuu508** [comment]
Thanks for the hint!

The Mattermost integration currently uses the exact same notification JSON template as Slack. We still list it as a separate integration, so it can have its own specific setup instructions, and also so that we have the option of using different notification templates. 

It would be similar with RocketChat – ideally we'd still want a separate integration with its own setup instructions, even if the JSON template is initially the same.

Also something I must keep in mind: when tweaking the Slack template, I should test Mattermost & RocketChat too!

**Comment by Dr-Shadow** [comment]
#785 is now adding a body in the message for mattermost integration which is not correctly supported when this integration is used with RocketChat.

The Slack integration has the same problem if used directly in RocketChat.

So, it seems the JSON template starts to need some tweaking

Example : 

![image](https://github.com/healthchecks/healthchecks/assets/5308086/4ef8486a-1a32-4943-81dc-588f8386edc3)

**Comment by cuu508** [comment]
I tried a few things but so far I haven't figured out a syntax that would work with Rocket.Chat. Multi-line pre-formatted text works in normal messages, and in the `text` field in message attachments, [but not inside `fields`](https://github.com/RocketChat/Rocket.Chat/issues/9625#issuecomment-1567941216).

What I can do for now is add a Rocket.Chat integration which posts the same payload as Mattermost, but exclude the last ping body field. Instead of showing badly formatted Last Ping Body, the notifications would then show no Last Ping Body.

**Comment by Dr-Shadow** [comment]
I'm getting this display because I didn't want to spend to much time around the attachment blocks.
I used an integration script to rewrite the json body received by rocket chat
![IMG_20230530_135023](https://github.com/healthchecks/healthchecks/assets/5308086/13bacbaa-3c8d-41dc-8170-5e55cd1669c1)

**Comment by Dr-Shadow** [comment]
I believe it would be better to use only 1 message for the entire alert. I'm fine with the body before the attachment

**Comment by Dr-Shadow** [comment]
You're right but our people at our company do not use the healtchecks website so they don't have an account on it :/

It would be a good idea to include a body the "test" hook from the integrations (especially mattermost and slack right now) so I can dig a bit further in the diagnosis as well.

**Comment by cuu508** [comment]
> You're right but our people at our company do not use the healtchecks website so they don't have an account on it :/

One possible solution is to invite them into the project. When inviting team members you can set the access level to read-only if that makes sense.

You can also set up email integrations for them, email notifications do contain the last ping body (well, first 10'000 bytes of it).

> It would be a good idea to include a body the "test" hook from the integrations (especially mattermost and slack right now) so I can dig a bit further in the diagnosis as well.

Yep, we could do that. Would you be testing how notifications look in different chat platforms, to decide which chat platform to use?

**Comment by Dr-Shadow** [comment]
> You can also set up email integrations for them, email notifications do contain the last ping body (well, first 10'000 bytes of it).

Yes, I am aware of it. I am already truncating my submitted log to the healthchecks api so that I only include the last 10'000 bytes

> Yep, we could do that. Would you be testing how notifications look in different chat platforms, to decide which chat platform to use?

Yes I was already planning to do that once I come back from my holiday leave next week :)

**Comment by cuu508** [comment]
I updated the notification template to show the last ping body size in bytes, and a link to view the full body:

![image](https://github.com/healthchecks/healthchecks/assets/661859/92ec061b-d8fe-4029-9d95-bf81bfa3afa7)

When or if Rocket.Chat improves the support for showing preformatted text, I'm happy to adjust the notification template.

**Comment by cuu508** [comment]
The initial version of the Rocket.Chat integration is ready for business, and is also deployed to the hosted service at https://healthchecks.io.
