### ISSUE TITLE
Checks move to "pause" state but receive their ping normally

### ISSUE THREAD

**Issue by danielsteigpayleven** [healthchecks/healthchecks#49]
Hi,
we are seeing quite a lot of checks in a pause state but we have no idea, how the pause state is defined and what it means. (Isn't mentioned in the docs) The checks get their ping regularly though.

Thanks for the help in advance.

best regards,

Daniel

**Comment by cuu508** [comment]
Do you see this on healthchecks.io or your own deployment?
If it's on your deployment, is your codebase maybe behind master?

The "paused"  state was used to disable checks when notification fails for any reason. Otherwise the notification would be retried and could potentially flood recipients with tons of emails. I've since changed this logic, and the "paused" state isn't used any more.

**Comment by danielsteigpayleven** [comment]
We are selfhosting it. Ah, then we are going to update next week and i let you know if this happens again.

Thanks for the quick update,

Daniel

**Comment by wojciecharabczykpayleven** [comment]
@cuu508 We've just updated to current master. Will let you know if the issue perists.
