### ISSUE TITLE
SMS message when service back UP not delivered

### ISSUE THREAD

**Issue by danemacmillan** [healthchecks/healthchecks#512]
This may be intentional, but I recently started testing the possibility of transitioning from Pushover to regular SMS, and I noticed that SMS only delivers DOWN notifications, but not notifications when a service comes back UP. Is this on purpose, or is this a bug?

I currently have both Pushover and SMS notifications configured, and that's how I noticed, because Pushover receives UP notifications.

**Comment by cuu508** [comment]
It was on purpose. My assumption was users would want to use SMS for more urgent messages since SMS has limited monthly quota, and SMS typically arrives in real time (not lazily, when you wake up a device, as emails sometimes would). And "DOWN" notifications would of course be more urgent than "UP". 

Looking at it with today's eyes, I think it's better to give users a choice, like we do with email notifications:

![image](https://user-images.githubusercontent.com/661859/119101505-bba87a80-ba21-11eb-8c58-a289e67132a7.png)

**Comment by cuu508** [comment]
FYI – I added the "Notify When" option for new SMS integrations, and deployed the change to https://healthchecks.io.

**Comment by danemacmillan** [comment]
Awesome, thanks! Always super responsive.
