### ISSUE TITLE
Add placeholder file for /static/img/logo-full@2x.png

### ISSUE THREAD

**Issue by SuperSandro2000** [healthchecks/healthchecks#550]
I noticed while setting up 2FA that ``/static/img/logo-full@2x.png`` has no placeholder file. Could you add one?

**Comment by cuu508** [comment]
It used to exist, I removed it when adding `SITE_LOGO_URL` setting – https://github.com/healthchecks/healthchecks/commit/2382bf6722dcb00d0d4ce1bc57b07cf9efaed154

Changes:
 
* There are no "logo" and "logo-full" variations any more. There's just one version of logo. Otherwise we would need `SITE_LOGO_URL` setting and also `SITE_LOGO_FULL_URL` setting.
* There are no regular and @2x variations. To get crisp rendering on high DPI screens, either use a larger png, or point `SITE_LOGO_URL` to a SVG file.

**Comment by cuu508** [comment]
Ah, OK, I understand the problem now. I had updated the base template for HTML pages, but forgot to update the email template, it was still referencing `logo-full@2x.png`. 

Fixed now: email template will use `SITE_LOGO_URL` if set, and fall back to `/static/img/logo.png`.
