### ISSUE TITLE
Bypass telegram rate limit using message grouping/queueing

### ISSUE THREAD

**Issue by ypapouin** [healthchecks/healthchecks#557]
Apparently, there is 30 msg/sec limit for a telegram bot.
When services depends on each others you can quickly reach this limit and have an inconsistent feedback state in your messaging app.

Since the minimal check unit is the minute, my proposal is to group check states changes in one message per project that would be sent every 60s if any. It implies to keep a queue of any state changes.

The other way is to also keep a global telegram queue and slowly dequeue it with a rate of one message every 2 seconds.

**Comment by cuu508** [comment]
I think the 6 messages per chat rate limit is reasonable. 

However, when, let's say 100 checks go down at once, there is a risk the user will receive 6 notifications, and will not realize there are 94 more failures – the problem is bigger. To help with that, I updated the Telegram notification template to also list other checks currently down:

![image](https://user-images.githubusercontent.com/661859/145232804-959e940f-aac1-4d81-9246-2da8e3dd01f0.png)
