### ISSUE TITLE
Webhook timeout

### ISSUE THREAD

**Issue by Sa6SFKPH8** [healthchecks/healthchecks#569]
Is there a way to set the timeout length for webhook integrations?

We have established a webhook to an internal service that works perfectly. The notification is sent and received 100% of the time. However when testing the webhook, 95+% of the time, the system indicates that the test failed and the integration is broken (screen capture attached). Very rarely, the system does acknowledge the test as successful so this appears to be a timeout issue. 

![2021-10-12_16-18-05](https://user-images.githubusercontent.com/7023234/137041775-4148f2d7-dc5f-4e29-9fa4-5c22fd3f2aee.jpg)

Finally, thanks for an immensely useful and elegant platform.

**Comment by cuu508** [comment]
I've now changed the timeout to 10 seconds and changed the retry logic to cap the max time spent to 20 seconds.

1. Start timer
1. Run the initial HTTP request with timeout=10
2. If the initial request fails or times out, retry with timeout=10
3. If the retry also fails, **and** we have spent less than 10 seconds since starting the timer, run the second retry.

In other words, the second retry may or may not run depending of how much time was spent on the initial try and the first retry.
