### ISSUE TITLE
Signal Integration Failing

### ISSUE THREAD

**Issue by azoller1** [healthchecks/healthchecks#632]
Related here: https://github.com/healthchecks/healthchecks/issues/564

I am receiving the same issues after registration and testing my signal integration. The number/account should be valid.

Could not send a test notification. signal-cli call failed (-1).

All other integrations for me work ok.

**Comment by bjo81** [comment]
I'm getting `Could not send a test notification. signal-cli call failed (-32602).` - I assume that's another issue?

**Comment by cuu508** [comment]
@bjo81 not sure, are you getting this on a self-hosted instance?

The first thing to check would be to see if you can send a message manually with signal-cli from command line. If that fails, the command's output may have clues on what's wrong.

**Comment by cuu508** [comment]
I've updated Healthchecks to handle Signal rate-limiting issues better. Instead of showing the non-specific "signa-cli call failed (-1)", Healthchecks now shows "CAPTCHA proof required". It also sends an alert to site administrators with more details. For administrators, there is also now a `submitchallenge` management command for submitting CAPTCHA solution.
