### ISSUE TITLE
Seeing Warnings prior to Timeout?

### ISSUE THREAD

**Issue by SlothCroissant** [healthchecks/healthchecks#676]
I'm seeing warnings throw up prior to my set timeout. It never throws a "down" error, just curious as to why I see warnings at all.

Env: Running in Docker, cron schedule set to `* * * * *`, with one minute grace period. 

What I'm seeing is warnings are being thrown prior to the one minute:

<img width="1334" alt="Screen Shot 2022-07-18 at 21 12 22" src="https://user-images.githubusercontent.com/5846854/179653209-710766b8-d7da-4a33-98b7-38e3371dca8c.png">

If I've received an checkin 49 seconds ago, and I'm expecting one check every minute, why would it throw a warning?

**Comment by cuu508** [comment]
With the `* * * * *` schedule, Healthchecks expects a ping **at the start** of every minute.

Let's say the client checks in 10 seconds past every minute. The timeline of events would go like this:

* 12:00:00 Healthchecks expects ping, status goes orange
* 12:00:10 ping arrives, status goes green
* 12:01:00 Healthchecks expects ping, status goes orange
* 12:01:10 ping arrives, status goes green
* 12:02:00 Healthchecks expects ping, status goes orange
* 12:02:10 ping arrives, status goes green
* ....

The check-in delay (10 seconds in the above example) can be because the cron job takes some time to execute, and also because system clocks may not be in perfect sync.

**Comment by SlothCroissant** [comment]
Thanks for the info! this clears it up nicely :)
