### ISSUE TITLE
Feature request: add ntfy as an integration

### ISSUE THREAD

**Issue by ksurl** [healthchecks/healthchecks#728]
https://ntfy.sh is a notification service that can be selfhosted or use the dev's hosted version.

**Comment by bt90** [comment]
https://github.com/healthchecks/healthchecks#apprise

https://github.com/caronc/apprise/wiki/Notify_ntfy

**Comment by ksurl** [comment]
is that only for selfhosted healthcheck instances? I don't see the option on healthchecks.io

**Comment by cuu508** [comment]
Yes, apprise is not enabled on Healthchecks.io. 

Currently, you can integrate with ntfy using the webhook integration: https://github.com/healthchecks/healthchecks/discussions/590

Since there's been several requests for it by now, I'll look into making a "native" integration, but cannot promise any timelines or deadlines. If you want it added quickly, submit a PR!

**Comment by ksurl** [comment]
I have not been able to get it to work with an authorization header for a password protected topic in a self hosted server

**Comment by cuu508** [comment]
I've implemented an initial version of the ntfy integration, and just deployed it to healthchecks.io. Testers welcome :-)

Note, the integration lets you specify a custom server URL, but does not let you specify username/password if you use ntfy [access control](https://docs.ntfy.sh/config/#access-control). A workaround is to still use webhook integration, like so:

![image](https://user-images.githubusercontent.com/661859/203797673-db872f22-03e9-418b-a4e1-961ca92db967.png)

(`Zm9vOmJhcg==` is base64("foo:bar"), update as needed)

**Comment by binwiederhier** [comment]
Very cool. Awesome @cuu508!

**Comment by tsrats** [comment]
Wanted to add an example for anyone who comes across this issue, who is also using authentication, and wants a more detailed alert than just the example provided by @cuu508. Add the following to the Request Headers section, substituting a green circle for red on the up if you wish. This is also an example of using a token instead of basic auth.
```
Authorization: Bearer <your token here>
Content-Type: text/markdown
X-Actions: view, View on <your site name here>, https://<your url here>/checks/$CODE/details
X-Tags: red_circle
```
It will look like this:
<img width="879" alt="Screenshot 2023-08-08 at 22 39 47" src="https://github.com/healthchecks/healthchecks/assets/91559398/2b4f86be-c3e7-4d15-a189-21aaf6380593">
