### ISSUE TITLE
Incorrect URL validation

### ISSUE THREAD

**Issue by micalm** [healthchecks/healthchecks#782]
When adding an integration, the URL sometimes is internal (when selfhosting), however healthchecks is reporting it as an invalid and returning a validation error.

For example - my ntfy topic is accessible via local DNS under `http://ntfy/healthcheck`. I would expect this to work. Same goes for webhooks.

One possible solution for URLs without the TLD (where `schema://domain.tld/`) would be to soft fail and instead of red error validation message on backend, display maybe an orange warning like "Double check your URL - it seems incomplete".

**Comment by cuu508** [comment]
Thanks for the report.

We have the [INTEGRATIONS_ALLOW_PRIVATE_IPS](https://healthchecks.io/docs/self_hosted_configuration/#INTEGRATIONS_ALLOW_PRIVATE_IPS) setting. It this setting is enabled, it would make sense to also relax URL validation rules. I'll see what can be done here.

In the meantime, as a workaround, you can use the IP address instead of the hostname in the URL.

**Comment by cuu508** [comment]
I've now fixed the URL validation code to allow URLs with just hostname and no domain or tld. `http://ntfy/healthcheck` should work now.

I did not tie the URL validation logic is not tied to the `INTEGRATIONS_ALLOW_PRIVATE_IPS` setting, because private IPs and "naked domains" are not the same thing:

* People can create a public DNS record for a private IP: `example.org A 192.168.0.1`.  
* And, conversely, people can use private DNS with records that point to public IPs: `ntfy A 1.2.3.4`
