### ISSUE TITLE
Add badges for individual checks

### ISSUE THREAD

**Issue by kiler129** [healthchecks/healthchecks#853]
It would be great to allow badges for individual checks. While there's a (documented) hack to assign a unique tag and get a badge for the tag, it doesn't really scale with hundreds of checks ;)

**Comment by mickBoat00** [comment]
What happens when a tag and check name are the same? The same url for svg will be generated for instance.
Possible solution is to enforce uniqueness between check names and tags for a project. Is there a better solution?

**Comment by mickBoat00** [comment]
What happens if a check name is the same as a tag for a different check in the same project. The same url will be generated for the svg for instance.Possible solution is solution is to enforce uniqueness between tags and different check names in a project. Is that good enough or there is a better solution?
