### ISSUE TITLE
Building a Docker image fails on Windows 10

### ISSUE THREAD

**Issue by kyxap** [healthchecks/healthchecks#857]
Hi there,
`>docker-compose up` fails on my windows 10 with:

```bash
 => [web stage-1 4/9] COPY --from=builder /wheels /wheels                                                          0.2s
 => [web stage-1 5/9] RUN     apt update &&     apt install -y libcurl4 libpq5 libmariadb3 libxml2 &&     rm -rf  10.1s
 => [web stage-1 6/9] RUN     pip install --upgrade pip &&     pip install --no-cache /wheels/*                   11.2s
 => [web stage-1 7/9] COPY --from=builder /opt/healthchecks/ /opt/healthchecks/                                    0.2s
 => ERROR [web stage-1 8/9] RUN     rm -f /opt/healthchecks/hc/local_settings.py &&     DEBUG=False SECRET_KEY=bu  0.7s
------
 > [web stage-1 8/9] RUN     rm -f /opt/healthchecks/hc/local_settings.py &&     DEBUG=False SECRET_KEY=build-key ./manage.py collectstatic --noinput &&     DEBUG=False SECRET_KEY=build-key ./manage.py compress:
#0 0.680 /usr/bin/env: ‘python\r’: No such file or directory
#0 0.680 /usr/bin/env: use -[v]S to pass options in shebang lines
------
time="2023-07-03T13:28:19-04:00" level=warning msg="buildx: git was not found in the system. Current commit information was not captured by the build"
failed to solve: process "/bin/sh -c rm -f /opt/healthchecks/hc/local_settings.py &&     DEBUG=False SECRET_KEY=build-key ./manage.py collectstatic --noinput &&     DEBUG=False SECRET_KEY=build-key ./manage.py compress" did not complete successfully: exit code: 127
```

yes I don't have `git` on that machine but is this actual issue? I don't see any requirements to be able get that running in docker.

using latest from master:
```bash
>git log
commit 1bfd1d22b0f2518e6a7a102e48e731d492456a4d (HEAD -> master, origin/master, origin/HEAD)
Author: Viktor Szépe <viktor@szepe.net>
Date:   Sun Jul 2 14:32:20 2023 +0200
```

UPD:
Steps to reproduce:
- `git clone` repo
- copy project to my box without git installed (via RDP)
- `cd healthchecks/docker`
- `cp .env.example .env`
- `vim .env` and upd all fields listed in wiki https://github.com/healthchecks/healthchecks/tree/master/docker#getting-started
- `docker-compose up` 
Expected: I got new image
Actual: failed with exception (see above)

**Comment by cuu508** [comment]
Thanks for the report. I tested the following:

* Installed WSL on a system running Windows 11 Home (`wsl --install` from administrator's command shell)
* Installed Docker Desktop (v4.21.1)
* Downloaded a snapshot of the Healthchecks source code from GitHub as a .zip file and extracted it
* In a PowerShell console, navigated to the extracted files, "docker" subdirectory, and ran `docker-compose-v1.exe up`

On the first run, I got errors about failed .deb downloads while building the image. I'm guessing this may have been caused by a network glitch. On the second run the image was built successfully and the container started up. I opened `http://localhost:8000` in the browser and saw the Healthchecks sign-in page running locally. 

Did you follow similar steps, or do you use a different setup? Can you try building the image again, in case the first build failed due to network problems, like in my case?

**Comment by kyxap** [comment]
@cuu508 hey, i've added steps to reproduce with all details, before posting this issue i've tried to build image multiple times and did it again today - same issue.

**Comment by cuu508** [comment]
The interesting part in docker-compose output is:

```
 > [web stage-1 8/9] RUN     rm -f /opt/healthchecks/hc/local_settings.py &&     DEBUG=False SECRET_KEY=build-key ./manage.py collectstatic --noinput &&     DEBUG=False SECRET_KEY=build-key ./manage.py compress:
#0 0.680 /usr/bin/env: ‘python\r’: No such file or directory
```

The first line of `manage.py` is:

```
#!/usr/bin/env python
```

In the git version, this line is terminated with a newline. The error message suggests that on your system it is terminated with a carriage return. Either the git clone process, or the copying via RDP seems to have messed up your source files.

**Comment by kyxap** [comment]
yeah you are correct, I've downloaded the direct zip to the win 10 and it seems to work.
sorry for bothering you!
