### ISSUE TITLE
API Call to check if another check (or more) is running

### ISSUE THREAD

**Issue by psyciknz** [healthchecks/healthchecks#871]
Working on a premise that I have two backup jobs I want to offset.  Check A would check healthchecks for if Check B is in a running state.  And therefore not run. 

Would that be possible with current API calls?

**Comment by cuu508** [comment]
Yes, the [Get a Single Check](https://healthchecks.io/docs/api/#get-check) API call response contains a boolean field `started` which tells if the check is in a running state.

I would not recommend using Healthchecks as a locking mechanism though. Potential problems with it:

* Reliability – if Healthchecks is down, it could prevent both Check A and Check B from running
* Race conditions:
  * Check A checks the running state, gets green light 
  * Check B checks the running state, gets green light
  * Check A sends `/start` signal
  * Check B sends `/start` signal
  * Both checks run concurrently
* Complexity and brittleness: your system now *depends* on Healthchecks, instead of using it as an optional, best-effort monitoring
