### ISSUE TITLE
Question: Grace period before ping?

### ISSUE THREAD

**Issue by Synt3x** [healthchecks/healthchecks#888]
Hello,

Looked through the documentation, but could not find anything about this. 

I was wondering if there is any way to add a grace period before a start ping. The reason for this is the following:

I'm managing a few tasks on different systems and to confirm that they are being executed at a specific time, I use healthchecks.

The problem that I'm am having is, that I have a daily task that should be started 01:00 and takes 10-30s to finish. But 1 of x system is running 1 minute in the future, so when its get triggered it will start and completed at 00:59 (healtcheck-server time). So then I first receive a notification that the previous job started and completed and then later the new daily failed

- The job is creates automatically by the task with the API. So the cron on the system is the same as healthchecks.
- I don't have access to change the time on the system.

This is why I'm asking if there is any grace period that you could add before an ping.

Thanks in advance!

/Robin

**Comment by Synt3x** [comment]
Hello @cuu508,

I understand if you busy and don't have time to answer this.
I'm  just wondering if you understood my question and if you have any suggestions.

Again thanks for your hard work.

/Robin

**Comment by cuu508** [comment]
I think I understand the issue:

* The client has wrong system time, and sends the success signal before the expected time (so the check fails after no signal at the expected time)
* You have an auto-provisioning system which prevents you from adjusting the cron expression in Healthchecks
* You cannot fix the client's system time

Healthchecks currently does not have anything that caters for pings arriving slightly too early. My typical advice is to fix system time on the client. If this is really, really not feasible, one workaround to consider would be to use the "simple" schedule instead of the "cron" schedule. Healthchecks will then monitor if the client reports in every X minutes, not at specific times.
