### ISSUE TITLE
Show number of monitors per tag

### ISSUE THREAD

**Issue by solracsf** [healthchecks/healthchecks#911]
![image](https://github.com/healthchecks/healthchecks/assets/12234510/241a606e-60c7-4b61-8bc6-452ea514ebc0)

Inside each tag box, show a number like in this example:

![image](https://github.com/healthchecks/healthchecks/assets/12234510/7263dc4e-5242-4992-a957-2b626f17f75b)

or hover

![image](https://github.com/healthchecks/healthchecks/assets/12234510/0bf037b7-ddcc-45e5-841f-0b2a5a93f870)

I think this can be helpful, and (hopefuly) not too hard to implement.
_("online" or "up", just a hint)_

Thanks 👍

**Comment by cuu508** [comment]
I've experimented with this a few times already, but I've never found a visually clean way to add the extra information.

The problem is, some people use *lots* of tags, and adding any extra information makes things look very noisy.

Consider this example:

![Screenshot from 2023-11-09 15-21-17](https://github.com/healthchecks/healthchecks/assets/661859/f41330b4-4095-470a-9047-59cf31bf58f4)

This is still relatively few tags. If we add a count on the right with a darker background:

![Screenshot from 2023-11-09 15-18-12](https://github.com/healthchecks/healthchecks/assets/661859/9ca33eb2-ab81-439a-99a2-17eb9c5ff9e6)

Border instead of background: 

![Screenshot from 2023-11-09 15-18-55](https://github.com/healthchecks/healthchecks/assets/661859/60dd9de5-91a4-4787-b504-32c9fe4dd2e9)

Muted text color instead of background or border:

![Screenshot from 2023-11-09 15-20-35](https://github.com/healthchecks/healthchecks/assets/661859/bea8f59b-28c3-42ad-93d4-a6e92a646554)

In each case, the tags area appears considerably more noisy. I think the last variant is least bad, but still not great.

**Comment by solracsf** [comment]
I see. I'll make some experiments and provide feedback if I can.

**Comment by solracsf** [comment]
What about integrate it as a tooltip on mouseover _(info is available and doesn't introduce noise)_?

**Comment by cuu508** [comment]
That's an idea!  It would be a bit hard to discover but it would certainly be unobtrusive.

**Comment by cuu508** [comment]
Initial implementation is ready, looks like so:

![image](https://github.com/healthchecks/healthchecks/assets/661859/a2012619-d429-4e14-b7ad-b44114564812)
