### ISSUE TITLE
Pause email notification

### ISSUE THREAD

**Issue by TakTaki** [healthchecks/healthchecks#94]
Hello,

Currently I have a CRON that is not working half of the time, I'm aware of that and I just don't want to receive mail every 10 minutes.
Is there a way to pause mail notification on a specific check?

Thanks

**Comment by cuu508** [comment]
What does your job's schedule look like?

There's issues #35 and #41 (support for cron syntax) which may be related. I've been putting off implementing this but looks like it's a genuinely needed feature.

**Comment by TakTaki** [comment]
My cron is a simple */5 * * * *, so I'm not really looking for a support of cron syntax. 

In my case, it's just that my cron work half the time so I can get more than a hundred mails a day. As the problem is not on my side, I just want to "pause" the mail notification and reactivate it when I'm told the problem is solved.

**Comment by cuu508** [comment]
aah, I see. And the existing "Pause" action doesn't help because next ping flips it back to unpaused.

You can go in the "Integrations" screen, look up your email and in the "Assigned Checks" dialog deselect the problematic check. It will keep receiving and logging pings but you will not be spammed with emails.

**Comment by TakTaki** [comment]
Wow, thanks ! That part was well hidden !

Thanks for the nice work and the response time !
