### ISSUE TITLE
Auto-refresh for Log page

### ISSUE THREAD

**Issue by asdffdsazqqq** [healthchecks/healthchecks#957]
hello and thanks for a great project.
currently, `https://healthchecks.io/checks/uuid/details` will auto-refresh the display as new checks come inbound.
however   `https://healthchecks.io/checks/0ea5c6f3-f103-4f85-9d6e-c40524578241/log/` will not auto-refresh.

so please, enable auto-refresh to log page.

thanks much, david

**Comment by cuu508** [comment]
@asdffdsazqqq implementing auto-refresh is doable, but [gets quite tricky complexity-wise](https://github.com/healthchecks/healthchecks/pull/963#issuecomment-1951139277) if we want to do it efficiently. 

We can also consider a smaller, simpler feature: after the log page is loaded, periodically check if there are any new events. If there are, instead of fetching and displaying them, show a message near the top of the page that says something like "There are new log events, reload the page to see them". This would be not as fancy, but much easier to implement. 

What are your thoughts, would the simpler feature be useful? Could it substitute full auto-refresh for you?
